const fs = require('fs');

const countriesData = [
  {"name":"Afghanistan","emoji":"🇦🇫","code":"+93","iso":"AF"},
  {"name":"Albania","emoji":"🇦🇱","code":"+355","iso":"AL"},
  {"name":"Algeria","emoji":"🇩🇿","code":"+213","iso":"DZ"},
  {"name":"American Samoa","emoji":"🇦🇸","code":"+1684","iso":"AS"},
  {"name":"Andorra","emoji":"🇦🇩","code":"+376","iso":"AD"},
  {"name":"Angola","emoji":"🇦🇴","code":"+244","iso":"AO"},
  {"name":"Anguilla","emoji":"🇦🇮","code":"+1264","iso":"AI"},
  {"name":"Antigua and Barbuda","emoji":"🇦🇬","code":"+1268","iso":"AG"},
  {"name":"Argentina","emoji":"🇦🇷","code":"+54","iso":"AR"},
  {"name":"Armenia","emoji":"🇦🇲","code":"+374","iso":"AM"},
  {"name":"Aruba","emoji":"🇦🇼","code":"+297","iso":"AW"},
  {"name":"Australia","emoji":"🇦🇺","code":"+61","iso":"AU"},
  {"name":"Austria","emoji":"🇦🇹","code":"+43","iso":"AT"},
  {"name":"Azerbaijan","emoji":"🇦🇿","code":"+994","iso":"AZ"},
  {"name":"Bahamas","emoji":"🇧🇸","code":"+1242","iso":"BS"},
  {"name":"Bahrain","emoji":"🇧🇭","code":"+973","iso":"BH"},
  {"name":"Bangladesh","emoji":"🇧🇩","code":"+880","iso":"BD"},
  {"name":"Barbados","emoji":"🇧🇧","code":"+1246","iso":"BB"},
  {"name":"Belarus","emoji":"🇧🇾","code":"+375","iso":"BY"},
  {"name":"Belgium","emoji":"🇧🇪","code":"+32","iso":"BE"},
  {"name":"Belize","emoji":"🇧🇿","code":"+501","iso":"BZ"},
  {"name":"Benin","emoji":"🇧🇯","code":"+229","iso":"BJ"},
  {"name":"Bermuda","emoji":"🇧🇲","code":"+1441","iso":"BM"},
  {"name":"Bhutan","emoji":"🇧🇹","code":"+975","iso":"BT"},
  {"name":"Bolivia","emoji":"🇧🇴","code":"+591","iso":"BO"},
  {"name":"Bosnia and Herzegovina","emoji":"🇧🇦","code":"+387","iso":"BA"},
  {"name":"Botswana","emoji":"🇧🇼","code":"+267","iso":"BW"},
  {"name":"Brazil","emoji":"🇧🇷","code":"+55","iso":"BR"},
  {"name":"British Indian Ocean Territory","emoji":"🇮🇴","code":"+246","iso":"IO"},
  {"name":"Bulgaria","emoji":"🇧🇬","code":"+359","iso":"BG"},
  {"name":"Burkina Faso","emoji":"🇧🇫","code":"+226","iso":"BF"},
  {"name":"Burundi","emoji":"🇧🇮","code":"+257","iso":"BI"},
  {"name":"Cambodia","emoji":"🇰🇭","code":"+855","iso":"KH"},
  {"name":"Cameroon","emoji":"🇨🇲","code":"+237","iso":"CM"},
  {"name":"Canada","emoji":"🇨🇦","code":"+1","iso":"CA"},
  {"name":"Cape Verde","emoji":"🇨🇻","code":"+238","iso":"CV"},
  {"name":"Cayman Islands","emoji":"🇰🇾","code":"+1345","iso":"KY"},
  {"name":"Central African Republic","emoji":"🇨🇫","code":"+236","iso":"CF"},
  {"name":"Chad","emoji":"🇹🇩","code":"+235","iso":"TD"},
  {"name":"Chile","emoji":"🇨🇱","code":"+56","iso":"CL"},
  {"name":"China","emoji":"🇨🇳","code":"+86","iso":"CN"},
  {"name":"Colombia","emoji":"🇨🇴","code":"+57","iso":"CO"},
  {"name":"Comoros","emoji":"🇰🇲","code":"+269","iso":"KM"},
  {"name":"Congo","emoji":"🇨🇬","code":"+242","iso":"CG"},
  {"name":"Costa Rica","emoji":"🇨🇷","code":"+506","iso":"CR"},
  {"name":"Croatia","emoji":"🇭🇷","code":"+385","iso":"HR"},
  {"name":"Cuba","emoji":"🇨🇺","code":"+53","iso":"CU"},
  {"name":"Cyprus","emoji":"🇨🇾","code":"+357","iso":"CY"},
  {"name":"Czech Republic","emoji":"🇨🇿","code":"+420","iso":"CZ"},
  {"name":"Denmark","emoji":"🇩🇰","code":"+45","iso":"DK"},
  {"name":"Djibouti","emoji":"🇩🇯","code":"+253","iso":"DJ"},
  {"name":"Dominica","emoji":"🇩🇲","code":"+1767","iso":"DM"},
  {"name":"Dominican Republic","emoji":"🇩🇴","code":"+1809","iso":"DO"},
  {"name":"Ecuador","emoji":"🇪🇨","code":"+593","iso":"EC"},
  {"name":"Egypt","emoji":"🇪🇬","code":"+20","iso":"EG"},
  {"name":"El Salvador","emoji":"🇸🇻","code":"+503","iso":"SV"},
  {"name":"Equatorial Guinea","emoji":"🇬🇶","code":"+240","iso":"GQ"},
  {"name":"Eritrea","emoji":"🇪🇷","code":"+291","iso":"ER"},
  {"name":"Estonia","emoji":"🇪🇪","code":"+372","iso":"EE"},
  {"name":"Ethiopia","emoji":"🇪🇹","code":"+251","iso":"ET"},
  {"name":"Falkland Islands","emoji":"🇫🇰","code":"+500","iso":"FK"},
  {"name":"Faroe Islands","emoji":"🇫🇴","code":"+298","iso":"FO"},
  {"name":"Fiji","emoji":"🇫🇯","code":"+679","iso":"FJ"},
  {"name":"Finland","emoji":"🇫🇮","code":"+358","iso":"FI"},
  {"name":"France","emoji":"🇫🇷","code":"+33","iso":"FR"},
  {"name":"Gabon","emoji":"🇬🇦","code":"+241","iso":"GA"},
  {"name":"Gambia","emoji":"🇬🇲","code":"+220","iso":"GM"},
  {"name":"Georgia","emoji":"🇬🇪","code":"+995","iso":"GE"},
  {"name":"Germany","emoji":"🇩🇪","code":"+49","iso":"DE"},
  {"name":"Ghana","emoji":"🇬🇭","code":"+233","iso":"GH"},
  {"name":"Gibraltar","emoji":"🇬🇮","code":"+350","iso":"GI"},
  {"name":"Greece","emoji":"🇬🇷","code":"+30","iso":"GR"},
  {"name":"Greenland","emoji":"🇬🇱","code":"+299","iso":"GL"},
  {"name":"Grenada","emoji":"🇬🇩","code":"+1473","iso":"GD"},
  {"name":"Guam","emoji":"🇬🇺","code":"+1671","iso":"GU"},
  {"name":"Guatemala","emoji":"🇬🇹","code":"+502","iso":"GT"},
  {"name":"Guinea","emoji":"🇬🇳","code":"+224","iso":"GN"},
  {"name":"Guinea-Bissau","emoji":"🇬🇼","code":"+245","iso":"GW"},
  {"name":"Guyana","emoji":"🇬🇾","code":"+592","iso":"GY"},
  {"name":"Haiti","emoji":"🇭🇹","code":"+509","iso":"HT"},
  {"name":"Honduras","emoji":"🇭🇳","code":"+504","iso":"HN"},
  {"name":"Hong Kong","emoji":"🇭🇰","code":"+852","iso":"HK"},
  {"name":"Hungary","emoji":"🇭🇺","code":"+36","iso":"HU"},
  {"name":"Iceland","emoji":"🇮🇸","code":"+354","iso":"IS"},
  {"name":"India","emoji":"🇮🇳","code":"+91","iso":"IN"},
  {"name":"Indonesia","emoji":"🇮🇩","code":"+62","iso":"ID"},
  {"name":"Iran","emoji":"🇮🇷","code":"+98","iso":"IR"},
  {"name":"Iraq","emoji":"🇮🇶","code":"+964","iso":"IQ"},
  {"name":"Ireland","emoji":"🇮🇪","code":"+353","iso":"IE"},
  {"name":"Israel","emoji":"🇮🇱","code":"+972","iso":"IL"},
  {"name":"Italy","emoji":"🇮🇹","code":"+39","iso":"IT"},
  {"name":"Jamaica","emoji":"🇯🇲","code":"+1876","iso":"JM"},
  {"name":"Japan","emoji":"🇯🇵","code":"+81","iso":"JP"},
  {"name":"Jordan","emoji":"🇯🇴","code":"+962","iso":"JO"},
  {"name":"Kazakhstan","emoji":"🇰🇿","code":"+7","iso":"KZ"},
  {"name":"Kenya","emoji":"🇰🇪","code":"+254","iso":"KE"},
  {"name":"Kiribati","emoji":"🇰🇮","code":"+686","iso":"KI"},
  {"name":"Kuwait","emoji":"🇰🇼","code":"+965","iso":"KW"},
  {"name":"Kyrgyzstan","emoji":"🇰🇬","code":"+996","iso":"KG"},
  {"name":"Laos","emoji":"🇱🇦","code":"+856","iso":"LA"},
  {"name":"Latvia","emoji":"🇱🇻","code":"+371","iso":"LV"},
  {"name":"Lebanon","emoji":"🇱🇧","code":"+961","iso":"LB"},
  {"name":"Lesotho","emoji":"🇱🇸","code":"+266","iso":"LS"},
  {"name":"Liberia","emoji":"🇱🇷","code":"+231","iso":"LR"},
  {"name":"Libya","emoji":"🇱🇾","code":"+218","iso":"LY"},
  {"name":"Liechtenstein","emoji":"🇱🇮","code":"+423","iso":"LI"},
  {"name":"Lithuania","emoji":"🇱🇹","code":"+370","iso":"LT"},
  {"name":"Luxembourg","emoji":"🇱🇺","code":"+352","iso":"LU"},
  {"name":"Macao","emoji":"🇲🇴","code":"+853","iso":"MO"},
  {"name":"Madagascar","emoji":"🇲🇬","code":"+261","iso":"MG"},
  {"name":"Malawi","emoji":"🇲🇼","code":"+265","iso":"MW"},
  {"name":"Malaysia","emoji":"🇲🇾","code":"+60","iso":"MY"},
  {"name":"Maldives","emoji":"🇲🇻","code":"+960","iso":"MV"},
  {"name":"Mali","emoji":"🇲🇱","code":"+223","iso":"ML"},
  {"name":"Malta","emoji":"🇲🇹","code":"+356","iso":"MT"},
  {"name":"Marshall Islands","emoji":"🇲🇭","code":"+692","iso":"MH"},
  {"name":"Mauritania","emoji":"🇲🇷","code":"+222","iso":"MR"},
  {"name":"Mauritius","emoji":"🇲🇺","code":"+230","iso":"MU"},
  {"name":"Mexico","emoji":"🇲🇽","code":"+52","iso":"MX"},
  {"name":"Micronesia","emoji":"🇫🇲","code":"+691","iso":"FM"},
  {"name":"Moldova","emoji":"🇲🇩","code":"+373","iso":"MD"},
  {"name":"Monaco","emoji":"🇲🇨","code":"+377","iso":"MC"},
  {"name":"Mongolia","emoji":"🇲🇳","code":"+976","iso":"MN"},
  {"name":"Montenegro","emoji":"🇲🇪","code":"+382","iso":"ME"},
  {"name":"Morocco","emoji":"🇲🇦","code":"+212","iso":"MA"},
  {"name":"Mozambique","emoji":"🇲🇿","code":"+258","iso":"MZ"},
  {"name":"Myanmar","emoji":"🇲🇲","code":"+95","iso":"MM"},
  {"name":"Namibia","emoji":"🇳🇦","code":"+264","iso":"NA"},
  {"name":"Nauru","emoji":"🇳🇷","code":"+674","iso":"NR"},
  {"name":"Nepal","emoji":"🇳🇵","code":"+977","iso":"NP"},
  {"name":"Netherlands","emoji":"🇳🇱","code":"+31","iso":"NL"},
  {"name":"New Zealand","emoji":"🇳🇿","code":"+64","iso":"NZ"},
  {"name":"Nicaragua","emoji":"🇳🇮","code":"+505","iso":"NI"},
  {"name":"Niger","emoji":"🇳🇪","code":"+227","iso":"NE"},
  {"name":"Nigeria","emoji":"🇳🇬","code":"+234","iso":"NG"},
  {"name":"North Korea","emoji":"🇰🇵","code":"+850","iso":"KP"},
  {"name":"North Macedonia","emoji":"🇲🇰","code":"+389","iso":"MK"},
  {"name":"Norway","emoji":"🇳🇴","code":"+47","iso":"NO"},
  {"name":"Oman","emoji":"🇴🇲","code":"+968","iso":"OM"},
  {"name":"Pakistan","emoji":"🇵🇰","code":"+92","iso":"PK"},
  {"name":"Palau","emoji":"🇵🇼","code":"+680","iso":"PW"},
  {"name":"Palestine","emoji":"🇵🇸","code":"+970","iso":"PS"},
  {"name":"Panama","emoji":"🇵🇦","code":"+507","iso":"PA"},
  {"name":"Papua New Guinea","emoji":"🇵🇬","code":"+675","iso":"PG"},
  {"name":"Paraguay","emoji":"🇵🇾","code":"+595","iso":"PY"},
  {"name":"Peru","emoji":"🇵🇪","code":"+51","iso":"PE"},
  {"name":"Philippines","emoji":"🇵🇭","code":"+63","iso":"PH"},
  {"name":"Poland","emoji":"🇵🇱","code":"+48","iso":"PL"},
  {"name":"Portugal","emoji":"🇵🇹","code":"+351","iso":"PT"},
  {"name":"Puerto Rico","emoji":"🇵🇷","code":"+1787","iso":"PR"},
  {"name":"Qatar","emoji":"🇶🇦","code":"+974","iso":"QA"},
  {"name":"Romania","emoji":"🇷🇴","code":"+40","iso":"RO"},
  {"name":"Russia","emoji":"🇷🇺","code":"+7","iso":"RU"},
  {"name":"Rwanda","emoji":"🇷🇼","code":"+250","iso":"RW"},
  {"name":"Samoa","emoji":"🇼🇸","code":"+685","iso":"WS"},
  {"name":"San Marino","emoji":"🇸🇲","code":"+378","iso":"SM"},
  {"name":"Saudi Arabia","emoji":"🇸🇦","code":"+966","iso":"SA"},
  {"name":"Senegal","emoji":"🇸🇳","code":"+221","iso":"SN"},
  {"name":"Serbia","emoji":"🇷🇸","code":"+381","iso":"RS"},
  {"name":"Seychelles","emoji":"🇸🇨","code":"+248","iso":"SC"},
  {"name":"Sierra Leone","emoji":"🇸🇱","code":"+232","iso":"SL"},
  {"name":"Singapore","emoji":"🇸🇬","code":"+65","iso":"SG"},
  {"name":"Slovakia","emoji":"🇸🇰","code":"+421","iso":"SK"},
  {"name":"Slovenia","emoji":"🇸🇮","code":"+386","iso":"SI"},
  {"name":"Solomon Islands","emoji":"🇸🇧","code":"+677","iso":"SB"},
  {"name":"Somalia","emoji":"🇸🇴","code":"+252","iso":"SO"},
  {"name":"South Africa","emoji":"🇿🇦","code":"+27","iso":"ZA"},
  {"name":"South Korea","emoji":"🇰🇷","code":"+82","iso":"KR"},
  {"name":"South Sudan","emoji":"🇸🇸","code":"+211","iso":"SS"},
  {"name":"Spain","emoji":"🇪🇸","code":"+34","iso":"ES"},
  {"name":"Sri Lanka","emoji":"🇱🇰","code":"+94","iso":"LK"},
  {"name":"Sudan","emoji":"🇸🇩","code":"+249","iso":"SD"},
  {"name":"Suriname","emoji":"🇸🇷","code":"+597","iso":"SR"},
  {"name":"Sweden","emoji":"🇸🇪","code":"+46","iso":"SE"},
  {"name":"Switzerland","emoji":"🇨🇭","code":"+41","iso":"CH"},
  {"name":"Syria","emoji":"🇸🇾","code":"+963","iso":"SY"},
  {"name":"Taiwan","emoji":"🇹🇼","code":"+886","iso":"TW"},
  {"name":"Tajikistan","emoji":"🇹🇯","code":"+992","iso":"TJ"},
  {"name":"Tanzania","emoji":"🇹🇿","code":"+255","iso":"TZ"},
  {"name":"Thailand","emoji":"🇹🇭","code":"+66","iso":"TH"},
  {"name":"Togo","emoji":"🇹🇬","code":"+228","iso":"TG"},
  {"name":"Tonga","emoji":"🇹🇴","code":"+676","iso":"TO"},
  {"name":"Trinidad and Tobago","emoji":"🇹🇹","code":"+1868","iso":"TT"},
  {"name":"Tunisia","emoji":"🇹🇳","code":"+216","iso":"TN"},
  {"name":"Turkey","emoji":"🇹🇷","code":"+90","iso":"TR"},
  {"name":"Turkmenistan","emoji":"🇹🇲","code":"+993","iso":"TM"},
  {"name":"Tuvalu","emoji":"🇹🇻","code":"+688","iso":"TV"},
  {"name":"Uganda","emoji":"🇺🇬","code":"+256","iso":"UG"},
  {"name":"Ukraine","emoji":"🇺🇦","code":"+380","iso":"UA"},
  {"name":"United Arab Emirates","emoji":"🇦🇪","code":"+971","iso":"AE"},
  {"name":"United Kingdom","emoji":"🇬🇧","code":"+44","iso":"GB"},
  {"name":"United States","emoji":"🇺🇸","code":"+1","iso":"US"},
  {"name":"Uruguay","emoji":"🇺🇾","code":"+598","iso":"UY"},
  {"name":"Uzbekistan","emoji":"🇺🇿","code":"+998","iso":"UZ"},
  {"name":"Vanuatu","emoji":"🇻🇺","code":"+678","iso":"VU"},
  {"name":"Venezuela","emoji":"🇻🇪","code":"+58","iso":"VE"},
  {"name":"Vietnam","emoji":"🇻🇳","code":"+84","iso":"VN"},
  {"name":"Yemen","emoji":"🇾🇪","code":"+967","iso":"YE"},
  {"name":"Zambia","emoji":"🇿🇲","code":"+260","iso":"ZM"},
  {"name":"Zimbabwe","emoji":"🇿🇼","code":"+263","iso":"ZW"}
];

let fileContent = `export const COUNTRY_CODES = ${JSON.stringify(countriesData, null, 2)};\n\n`;
fileContent += `export function parsePhoneWithCountry(fullPhone: string) {
  if (!fullPhone) return { countryCode: '+92', number: '' };
  
  const match = fullPhone.match(/^(\\+\\d{1,4})\\s*(.*)/);
  if (match) {
    const code = match[1];
    return { countryCode: code, number: match[2].trim() };
  }
  
  return { countryCode: '+92', number: fullPhone.trim() };
}\n`;

fs.writeFileSync('src/utils/countries.ts', fileContent, 'utf8');
console.log('Generated src/utils/countries.ts');
