export interface Country {
  name: string;
  code: string;
  iso: string;
  emoji: string;
}

export const COUNTRY_CODES: Country[] = [
  { name: 'Afghanistan', code: '+93', iso: 'AF', emoji: '🇦🇫' },
  { name: 'Albania', code: '+355', iso: 'AL', emoji: '🇦🇱' },
  { name: 'Algeria', code: '+213', iso: 'DZ', emoji: '🇩🇿' },
  { name: 'Andorra', code: '+376', iso: 'AD', emoji: '🇦🇩' },
  { name: 'Angola', code: '+244', iso: 'AO', emoji: '🇦🇴' },
  { name: 'Antigua and Barbuda', code: '+1', iso: 'AG', emoji: '🇦🇬' },
  { name: 'Argentina', code: '+54', iso: 'AR', emoji: '🇦🇷' },
  { name: 'Armenia', code: '+374', iso: 'AM', emoji: '🇦🇲' },
  { name: 'Australia', code: '+61', iso: 'AU', emoji: '🇦🇺' },
  { name: 'Austria', code: '+43', iso: 'AT', emoji: '🇦🇹' },
  { name: 'Azerbaijan', code: '+994', iso: 'AZ', emoji: '🇦🇿' },
  { name: 'Bahamas', code: '+1', iso: 'BS', emoji: '🇧🇸' },
  { name: 'Bahrain', code: '+973', iso: 'BH', emoji: '🇧🇭' },
  { name: 'Bangladesh', code: '+880', iso: 'BD', emoji: '🇧🇩' },
  { name: 'Barbados', code: '+1', iso: 'BB', emoji: '🇧🇧' },
  { name: 'Belarus', code: '+375', iso: 'BY', emoji: '🇧🇾' },
  { name: 'Belgium', code: '+32', iso: 'BE', emoji: '🇧🇪' },
  { name: 'Belize', code: '+501', iso: 'BZ', emoji: '🇧🇿' },
  { name: 'Benin', code: '+229', iso: 'BJ', emoji: '🇧🇯' },
  { name: 'Bhutan', code: '+975', iso: 'BT', emoji: '🇧🇹' },
  { name: 'Bolivia', code: '+591', iso: 'BO', emoji: '🇧🇴' },
  { name: 'Bosnia and Herzegovina', code: '+387', iso: 'BA', emoji: '🇧🇦' },
  { name: 'Botswana', code: '+267', iso: 'BW', emoji: '🇧🇼' },
  { name: 'Brazil', code: '+55', iso: 'BR', emoji: '🇧🇷' },
  { name: 'Brunei', code: '+673', iso: 'BN', emoji: '🇧🇳' },
  { name: 'Bulgaria', code: '+359', iso: 'BG', emoji: '🇧🇬' },
  { name: 'Burkina Faso', code: '+226', iso: 'BF', emoji: '🇧🇫' },
  { name: 'Burundi', code: '+257', iso: 'BI', emoji: '🇧🇮' },
  { name: 'Cabo Verde', code: '+238', iso: 'CV', emoji: '🇨🇻' },
  { name: 'Cambodia', code: '+855', iso: 'KH', emoji: '🇰🇭' },
  { name: 'Cameroon', code: '+237', iso: 'CM', emoji: '🇨🇲' },
  { name: 'Canada', code: '+1', iso: 'CA', emoji: '🇨🇦' },
  { name: 'Central African Republic', code: '+236', iso: 'CF', emoji: '🇨🇫' },
  { name: 'Chad', code: '+235', iso: 'TD', emoji: '🇹🇩' },
  { name: 'Chile', code: '+56', iso: 'CL', emoji: '🇨🇱' },
  { name: 'China', code: '+86', iso: 'CN', emoji: '🇨🇳' },
  { name: 'Colombia', code: '+57', iso: 'CO', emoji: '🇨🇴' },
  { name: 'Comoros', code: '+269', iso: 'KM', emoji: '🇰🇲' },
  { name: 'Congo', code: '+242', iso: 'CG', emoji: '🇨🇬' },
  { name: 'Costa Rica', code: '+506', iso: 'CR', emoji: '🇨🇷' },
  { name: 'Croatia', code: '+385', iso: 'HR', emoji: '🇭🇷' },
  { name: 'Cuba', code: '+53', iso: 'CU', emoji: '🇨🇺' },
  { name: 'Cyprus', code: '+357', iso: 'CY', emoji: '🇨🇾' },
  { name: 'Czech Republic', code: '+420', iso: 'CZ', emoji: '🇨🇿' },
  { name: 'Denmark', code: '+45', iso: 'DK', emoji: '🇩🇰' },
  { name: 'Djibouti', code: '+253', iso: 'DJ', emoji: '🇩🇯' },
  { name: 'Dominica', code: '+1', iso: 'DM', emoji: '🇩🇲' },
  { name: 'Dominican Republic', code: '+1', iso: 'DO', emoji: '🇩🇴' },
  { name: 'Ecuador', code: '+593', iso: 'EC', emoji: '🇪🇨' },
  { name: 'Egypt', code: '+20', iso: 'EG', emoji: '🇪🇬' },
  { name: 'El Salvador', code: '+503', iso: 'SV', emoji: '🇸🇻' },
  { name: 'Equatorial Guinea', code: '+240', iso: 'GQ', emoji: '🇬🇶' },
  { name: 'Eritrea', code: '+291', iso: 'ER', emoji: '🇪🇷' },
  { name: 'Estonia', code: '+372', iso: 'EE', emoji: '🇪🇪' },
  { name: 'Eswatini', code: '+268', iso: 'SZ', emoji: '🇸🇿' },
  { name: 'Ethiopia', code: '+251', iso: 'ET', emoji: '🇪🇹' },
  { name: 'Fiji', code: '+679', iso: 'FJ', emoji: '🇫🇯' },
  { name: 'Finland', code: '+358', iso: 'FI', emoji: '🇫🇮' },
  { name: 'France', code: '+33', iso: 'FR', emoji: '🇫🇷' },
  { name: 'Gabon', code: '+241', iso: 'GA', emoji: '🇬🇦' },
  { name: 'Gambia', code: '+220', iso: 'GM', emoji: '🇬🇲' },
  { name: 'Georgia', code: '+995', iso: 'GE', emoji: '🇬🇪' },
  { name: 'Germany', code: '+49', iso: 'DE', emoji: '🇩🇪' },
  { name: 'Ghana', code: '+233', iso: 'GH', emoji: '🇬🇭' },
  { name: 'Greece', code: '+30', iso: 'GR', emoji: '🇬🇷' },
  { name: 'Grenada', code: '+1', iso: 'GD', emoji: '🇬🇩' },
  { name: 'Guatemala', code: '+502', iso: 'GT', emoji: '🇬🇹' },
  { name: 'Guinea', code: '+224', iso: 'GN', emoji: '🇬🇳' },
  { name: 'Guinea-Bissau', code: '+245', iso: 'GW', emoji: '🇬🇼' },
  { name: 'Guyana', code: '+592', iso: 'GY', emoji: '🇬🇾' },
  { name: 'Haiti', code: '+509', iso: 'HT', emoji: '🇭🇹' },
  { name: 'Honduras', code: '+504', iso: 'HN', emoji: '🇭🇳' },
  { name: 'Hungary', code: '+36', iso: 'HU', emoji: '🇭🇺' },
  { name: 'Iceland', code: '+354', iso: 'IS', emoji: '🇮🇸' },
  { name: 'India', code: '+91', iso: 'IN', emoji: '🇮🇳' },
  { name: 'Indonesia', code: '+62', iso: 'ID', emoji: '🇮🇩' },
  { name: 'Iran', code: '+98', iso: 'IR', emoji: '🇮🇷' },
  { name: 'Iraq', code: '+964', iso: 'IQ', emoji: '🇮🇶' },
  { name: 'Ireland', code: '+353', iso: 'IE', emoji: '🇮🇪' },
  { name: 'Israel', code: '+972', iso: 'IL', emoji: '🇮🇱' },
  { name: 'Italy', code: '+39', iso: 'IT', emoji: '🇮🇹' },
  { name: 'Jamaica', code: '+1', iso: 'JM', emoji: '🇯🇲' },
  { name: 'Japan', code: '+81', iso: 'JP', emoji: '🇯🇵' },
  { name: 'Jordan', code: '+962', iso: 'JO', emoji: '🇯🇴' },
  { name: 'Kazakhstan', code: '+7', iso: 'KZ', emoji: '🇰🇿' },
  { name: 'Kenya', code: '+254', iso: 'KE', emoji: '🇰🇪' },
  { name: 'Kiribati', code: '+686', iso: 'KI', emoji: '🇰🇮' },
  { name: 'Kuwait', code: '+965', iso: 'KW', emoji: '🇰🇼' },
  { name: 'Kyrgyzstan', code: '+996', iso: 'KG', emoji: '🇰🇬' },
  { name: 'Laos', code: '+856', iso: 'LA', emoji: '🇱🇦' },
  { name: 'Latvia', code: '+371', iso: 'LV', emoji: '🇱🇻' },
  { name: 'Lebanon', code: '+961', iso: 'LB', emoji: '🇱🇧' },
  { name: 'Lesotho', code: '+266', iso: 'LS', emoji: '🇱🇸' },
  { name: 'Liberia', code: '+231', iso: 'LR', emoji: '🇱🇷' },
  { name: 'Libya', code: '+218', iso: 'LY', emoji: '🇱🇾' },
  { name: 'Liechtenstein', code: '+423', iso: 'LI', emoji: '🇱🇮' },
  { name: 'Lithuania', code: '+370', iso: 'LT', emoji: '🇱🇹' },
  { name: 'Luxembourg', code: '+352', iso: 'LU', emoji: '🇱🇺' },
  { name: 'Madagascar', code: '+261', iso: 'MG', emoji: '🇲🇬' },
  { name: 'Malawi', code: '+265', iso: 'MW', emoji: '🇲🇼' },
  { name: 'Malaysia', code: '+60', iso: 'MY', emoji: '🇲🇾' },
  { name: 'Maldives', code: '+960', iso: 'MV', emoji: '🇲🇻' },
  { name: 'Mali', code: '+223', iso: 'ML', emoji: '🇲🇱' },
  { name: 'Malta', code: '+356', iso: 'MT', emoji: '🇲🇹' },
  { name: 'Marshall Islands', code: '+692', iso: 'MH', emoji: '🇲🇭' },
  { name: 'Mauritania', code: '+222', iso: 'MR', emoji: '🇲🇷' },
  { name: 'Mauritius', code: '+230', iso: 'MU', emoji: '🇲🇺' },
  { name: 'Mexico', code: '+52', iso: 'MX', emoji: '🇲🇽' },
  { name: 'Micronesia', code: '+691', iso: 'FM', emoji: '🇫🇲' },
  { name: 'Moldova', code: '+373', iso: 'MD', emoji: '🇲🇩' },
  { name: 'Monaco', code: '+377', iso: 'MC', emoji: '🇲🇨' },
  { name: 'Mongolia', code: '+976', iso: 'MN', emoji: '🇲🇳' },
  { name: 'Montenegro', code: '+382', iso: 'ME', emoji: '🇲🇪' },
  { name: 'Morocco', code: '+212', iso: 'MA', emoji: '🇲🇦' },
  { name: 'Mozambique', code: '+258', iso: 'MZ', emoji: '🇲🇿' },
  { name: 'Myanmar', code: '+95', iso: 'MM', emoji: '🇲🇲' },
  { name: 'Namibia', code: '+264', iso: 'NA', emoji: '🇳🇦' },
  { name: 'Nauru', code: '+674', iso: 'NR', emoji: '🇳🇷' },
  { name: 'Nepal', code: '+977', iso: 'NP', emoji: '🇳🇵' },
  { name: 'Netherlands', code: '+31', iso: 'NL', emoji: '🇳🇱' },
  { name: 'New Zealand', code: '+64', iso: 'NZ', emoji: '🇳🇿' },
  { name: 'Nicaragua', code: '+505', iso: 'NI', emoji: '🇳🇮' },
  { name: 'Niger', code: '+227', iso: 'NE', emoji: '🇳🇪' },
  { name: 'Nigeria', code: '+234', iso: 'NG', emoji: '🇳🇬' },
  { name: 'North Korea', code: '+850', iso: 'KP', emoji: '🇰🇵' },
  { name: 'North Macedonia', code: '+389', iso: 'MK', emoji: '🇲🇰' },
  { name: 'Norway', code: '+47', iso: 'NO', emoji: '🇳🇴' },
  { name: 'Oman', code: '+968', iso: 'OM', emoji: '🇴🇲' },
  { name: 'Pakistan', code: '+92', iso: 'PK', emoji: '🇵🇰' },
  { name: 'Palau', code: '+680', iso: 'PW', emoji: '🇵🇼' },
  { name: 'Palestine', code: '+970', iso: 'PS', emoji: '🇵🇸' },
  { name: 'Panama', code: '+507', iso: 'PA', emoji: '🇵🇦' },
  { name: 'Papua New Guinea', code: '+675', iso: 'PG', emoji: '🇵🇬' },
  { name: 'Paraguay', code: '+595', iso: 'PY', emoji: '🇵🇾' },
  { name: 'Peru', code: '+51', iso: 'PE', emoji: '🇵🇪' },
  { name: 'Philippines', code: '+63', iso: 'PH', emoji: '🇵🇭' },
  { name: 'Poland', code: '+48', iso: 'PL', emoji: '🇵🇱' },
  { name: 'Portugal', code: '+351', iso: 'PT', emoji: '🇵🇹' },
  { name: 'Qatar', code: '+974', iso: 'QA', emoji: '🇶🇦' },
  { name: 'Romania', code: '+40', iso: 'RO', emoji: '🇷🇴' },
  { name: 'Russia', code: '+7', iso: 'RU', emoji: '🇷🇺' },
  { name: 'Rwanda', code: '+250', iso: 'RW', emoji: '🇷🇼' },
  { name: 'Saint Kitts and Nevis', code: '+1', iso: 'KN', emoji: '🇰🇳' },
  { name: 'Saint Lucia', code: '+1', iso: 'LC', emoji: '🇱🇨' },
  { name: 'Saint Vincent and the Grenadines', code: '+1', iso: 'VC', emoji: '🇻🇨' },
  { name: 'Samoa', code: '+685', iso: 'WS', emoji: '🇼🇸' },
  { name: 'San Marino', code: '+378', iso: 'SM', emoji: '🇸🇲' },
  { name: 'Sao Tome and Principe', code: '+239', iso: 'ST', emoji: '🇸🇹' },
  { name: 'Saudi Arabia', code: '+966', iso: 'SA', emoji: '🇸🇦' },
  { name: 'Senegal', code: '+221', iso: 'SN', emoji: '🇸🇳' },
  { name: 'Serbia', code: '+381', iso: 'RS', emoji: '🇷🇸' },
  { name: 'Seychelles', code: '+248', iso: 'SC', emoji: '🇸🇨' },
  { name: 'Sierra Leone', code: '+232', iso: 'SL', emoji: '🇸🇱' },
  { name: 'Singapore', code: '+65', iso: 'SG', emoji: '🇸🇬' },
  { name: 'Slovakia', code: '+421', iso: 'SK', emoji: '🇸🇰' },
  { name: 'Slovenia', code: '+386', iso: 'SI', emoji: '🇸🇮' },
  { name: 'Solomon Islands', code: '+677', iso: 'SB', emoji: '🇸🇧' },
  { name: 'Somalia', code: '+252', iso: 'SO', emoji: '🇸🇴' },
  { name: 'South Africa', code: '+27', iso: 'ZA', emoji: '🇿🇦' },
  { name: 'South Korea', code: '+82', iso: 'KR', emoji: '🇰🇷' },
  { name: 'South Sudan', code: '+211', iso: 'SS', emoji: '🇸🇸' },
  { name: 'Spain', code: '+34', iso: 'ES', emoji: '🇪🇸' },
  { name: 'Sri Lanka', code: '+94', iso: 'LK', emoji: '🇱🇰' },
  { name: 'Sudan', code: '+249', iso: 'SD', emoji: '🇸🇩' },
  { name: 'Suriname', code: '+597', iso: 'SR', emoji: '🇸🇷' },
  { name: 'Sweden', code: '+46', iso: 'SE', emoji: '🇸🇪' },
  { name: 'Switzerland', code: '+41', iso: 'CH', emoji: '🇨🇭' },
  { name: 'Syria', code: '+963', iso: 'SY', emoji: '🇸🇾' },
  { name: 'Taiwan', code: '+886', iso: 'TW', emoji: '🇹🇼' },
  { name: 'Tajikistan', code: '+992', iso: 'TJ', emoji: '🇹🇯' },
  { name: 'Tanzania', code: '+255', iso: 'TZ', emoji: '🇹🇿' },
  { name: 'Thailand', code: '+66', iso: 'TH', emoji: '🇹🇭' },
  { name: 'Timor-Leste', code: '+670', iso: 'TL', emoji: '🇹🇱' },
  { name: 'Togo', code: '+228', iso: 'TG', emoji: '🇹🇬' },
  { name: 'Tonga', code: '+676', iso: 'TO', emoji: '🇹🇴' },
  { name: 'Trinidad and Tobago', code: '+1', iso: 'TT', emoji: '🇹🇹' },
  { name: 'Tunisia', code: '+216', iso: 'TN', emoji: '🇹🇳' },
  { name: 'Turkey', code: '+90', iso: 'TR', emoji: '🇹🇷' },
  { name: 'Turkmenistan', code: '+993', iso: 'TM', emoji: '🇹🇲' },
  { name: 'Tuvalu', code: '+688', iso: 'TV', emoji: '🇹🇻' },
  { name: 'Uganda', code: '+256', iso: 'UG', emoji: '🇺🇬' },
  { name: 'Ukraine', code: '+380', iso: 'UA', emoji: '🇺🇦' },
  { name: 'United Arab Emirates', code: '+971', iso: 'AE', emoji: '🇦🇪' },
  { name: 'United Kingdom', code: '+44', iso: 'GB', emoji: '🇬🇧' },
  { name: 'United States', code: '+1', iso: 'US', emoji: '🇺🇸' },
  { name: 'Uruguay', code: '+598', iso: 'UY', emoji: '🇺🇾' },
  { name: 'Uzbekistan', code: '+998', iso: 'UZ', emoji: '🇺🇿' },
  { name: 'Vanuatu', code: '+678', iso: 'VU', emoji: '🇻🇺' },
  { name: 'Vatican City', code: '+379', iso: 'VA', emoji: '🇻🇦' },
  { name: 'Venezuela', code: '+58', iso: 'VE', emoji: '🇻🇪' },
  { name: 'Vietnam', code: '+84', iso: 'VN', emoji: '🇻🇳' },
  { name: 'Yemen', code: '+967', iso: 'YE', emoji: '🇾🇪' },
  { name: 'Zambia', code: '+260', iso: 'ZM', emoji: '🇿🇲' },
  { name: 'Zimbabwe', code: '+263', iso: 'ZW', emoji: '🇿🇼' }
];

export function parsePhoneWithCountry(fullPhone: string) {
  if (!fullPhone) return { countryCode: '+92', number: '' };
  
  const match = fullPhone.match(/^(\+\d{1,4})\s*(.*)/);
  if (match) {
    const code = match[1];
    return { countryCode: code, number: match[2].trim() };
  }
  
  return { countryCode: '+92', number: fullPhone.trim() };
}
